### ISSUE TITLE
Tornado Integration

### ISSUE THREAD

**Issue by stgleb** [IsCoolEntertainment/pynba#11]
Hello, is it possible to implement pynba integration with tornado to monitor non-wsgi applications.

**Comment by steffgrez** [comment]
hello,

first, be careful, this package is deprecated. You can find new version here:
https://github.com/johnnoone/pynba

Anyway, for a tornado application, have you try to use directly the ScriptMonitor object ?
https://github.com/johnnoone/pynba/blob/master/pynba/util/script.py
